country_tests = [
     { 'name': "1 - Pipeline/identification projects",
       'expression': 'activity-status/@code is 1?', },
     { 'name': "1 - Economic classification",
       'expression': 'capital-spend exists (if activity-status/@code is at least 2 and (default-aid-type/@code or transaction/aid-type/@code is not A01 or A02))?', },
     { 'name': "1 - Functional/administrative classification",
       'expression': 'at least one country-budget-items[@vocabulary="1"]/budget-item/@code is on list BudgetIdentifier (if activity-status/@code is at least 2 and (default-aid-type/@code or transaction/aid-type/@code is not A01 or A02))?', },
     { 'name': "2 - Results",
       'expression': 'result exists (if activity-status/@code is at least 2)?', },
     { 'name': "2 - Evaluations",
       'expression': "document-link/category[@code='A07'] exists (if activity-status/@code is at least 3)?", },
     { 'name': "3 - Fwd budgets",
       'expression': 'budget or planned-disbursement is available forward (if activity-status/@code is at least 2)?', },
     { 'name': "3 - Conditionality",
       'expression': 'conditions exists (if activity-status/@code is at least 2)?', },
     { 'name': "4 - Disbursement channel",
       'expression': 'transaction/disbursement-channel/@code exists (if activity-status/@code is at least 2)?', },
     { 'name': "4 - Type of implementing org",
       'expression': 'participating-org[@role="Implementing"]/@type exists (if activity-status/@code is at least 2)?', },
     { 'name': "5 - Sector",
       'expression': 'at least one (sector[@vocabulary="DAC"]/@code or sector[not(@vocabulary)]/@code) is on list Sector?', },
     { 'name': "5 - Sub-national location",
       'expression': 'location/coordinates or location/point exists (if activity-status/@code is at least 2 and recipient-region/@code is not 998)?', },
    ]

exclude_hierarchies = {
    '41114': {
        "1 - Pipeline/identification projects": "2",
        "1 - Economic classification": '1',
        "1 - Functional/administrative classification": '1',
        "2 - Results": '1',
        "2 - Evaluations": '2',
        "3 - Fwd budgets": '1',
        "3 - Conditionality": '2',
        "4 - Disbursement channel": '1',
        "4 - Type of implementing org": '2',
        "5 - Sector": '1',
        "5 - Sub-national location": '1',
    },
    'GB-1': {
        "1 - Economic classification": '1',
        "1 - Functional/administrative classification": '1',
        "2 - Results": '2',
        "2 - Evaluations": '2',
        "3 - Fwd budgets": '1',
        "3 - Conditionality": '2',
        "4 - Disbursement channel": '1',
        "4 - Type of implementing org": '1',
        "5 - Sector": '1',
        "5 - Sub-national location": '2',
    },
    'SE-6': {
        "1 - Economic classification": '1',
        "1 - Functional/administrative classification": '1',
        "2 - Results": '1',
        "2 - Evaluations": '1',
        "4 - Disbursement channel": '1',
        "4 - Type of implementing org": '1',
        "5 - Sector": '1',
        "5 - Sub-national location": '1',
    }
}
currency_usd = {
    "USD": 1,
    "XDR": 1.50154,
    "EUR": 1.28987,
    "eur": 1.28987,
    "GBP": 1.60971,
    "DKK": 0.173259,
    "JPY": 0.00943802,
    "CAD": 0.910902,
    "AUD": 0.928075,
    "NZD": 0.828119,
}

